global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:

alerting:

scrape_configs:
  - job_name: 'graphnode-metrics'
    metrics_path: /metrics
    static_configs:
      - targets: ['graphnode-indexer-1:8040', 'graphnode-query-1:8040']
  - job_name: 'indexer-service-metrics'
    metrics_path: /metrics
    static_configs:
      - targets: ['indexer-service:7300']
  - job_name: 'indexer-agent-metrics'
    metrics_path: /metrics
    static_configs:
      - targets: ['indexer-service:7300']
 
