global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:

alerting:

scrape_configs:
  - job_name: 'graphnode-indexer-1-metrics'
    metrics_path: /metrics
    static_configs:
      - targets: ['graphnode-indexer-1:8040']

